-- Add detailed criteria scores for the mock deals (fixed UUID)
INSERT INTO criteria_scores (deal_id, criterion, score, confidence, rationale, evidence, missing_data, raw) VALUES

-- NeuralFlow AI (550e8400-e29b-41d4-a716-446655440001) criteria scores
('550e8400-e29b-41d4-a716-446655440001', 'Team', 1.8, 0.92, 'Exceptional founding team with Sarah Chen (ex-Google AI) as CTO and Mark Rodriguez (former Databricks VP) as CEO. Team has 3 previous exits totaling $2.1B. Strong technical depth with 15 engineers, 8 with PhDs in ML/AI.', 'LinkedIn profiles show extensive AI/ML experience. Previous companies: Google, Meta, OpenAI. 2 team members published 50+ papers in top-tier AI conferences. CEO previously scaled Databricks from 50 to 1000+ employees.', 'Some uncertainty about equity distribution among founders and employee retention strategies.', '{"team_size": 23, "founders": 3, "technical_team": 15, "previous_exits": 3, "total_exit_value": 2100000000}'),

('550e8400-e29b-41d4-a716-446655440001', 'Business Model', 2.1, 0.88, 'Strong B2B SaaS model with usage-based pricing tiers. Clear value proposition of reducing data pipeline costs by 40-60%. Multiple revenue streams: platform licensing, professional services, and data marketplace.', 'Current pricing: $5k-50k monthly depending on data volume. 89% gross margins. 3 pricing tiers with clear upgrade paths. Letters of intent from 12 enterprise customers worth $8.2M ARR.', 'Limited information on customer acquisition costs and churn rates for the usage-based model.', '{"pricing_model": "usage_based", "gross_margin": 0.89, "revenue_streams": 3, "loi_value": 8200000}'),

('550e8400-e29b-41d4-a716-446655440001', 'Technology', 1.5, 0.95, 'Cutting-edge proprietary ML algorithms for automated data pipeline optimization. 15 patents filed, 8 granted. Technology benchmarks show 3x performance improvement over competitors like Palantir and Snowflake.', 'Independent benchmarks by Gartner show 67% faster data processing. Technology stack: Kubernetes, Apache Spark, custom ML models. Code base: 450k lines, 94% test coverage. Security: SOC2 Type II compliant.', 'None identified - comprehensive technical due diligence completed.', '{"patents_filed": 15, "patents_granted": 8, "performance_vs_competitors": "3x", "test_coverage": 0.94}'),

('550e8400-e29b-41d4-a716-446655440001', 'Product', 2.0, 0.91, 'Mature product with strong user adoption. Dashboard shows excellent UX/UI design. 94% user satisfaction score. Product roadmap shows clear evolution toward AI-native data platform.', 'Customer NPS score: 67. Feature adoption rate: 82% for core features. 15 customer case studies showing measurable ROI. Product demo received positive feedback from 23/25 technical evaluators.', 'Some concern about feature bloat and maintaining simplicity as product expands.', '{"nps_score": 67, "user_satisfaction": 0.94, "feature_adoption": 0.82, "case_studies": 15}'),

('550e8400-e29b-41d4-a716-446655440001', 'Geography', 2.8, 0.85, 'Based in San Francisco with strong presence in North American market. Some international expansion started in UK and Germany. Geographic focus aligns well with our portfolio strategy.', 'San Francisco HQ, 87% of customers in North America. UK office opened 6 months ago with 3 customers signed. German pilot program with 2 enterprise prospects.', 'International expansion strategy lacks detail. Regulatory compliance in EU markets needs clarification.', '{"primary_market": "North America", "customer_distribution": {"NA": 0.87, "EU": 0.13}, "international_offices": 1}'),

('550e8400-e29b-41d4-a716-446655440001', 'Monetization', 1.9, 0.90, 'Multiple monetization channels with clear pricing power. Usage-based model scales naturally with customer growth. Professional services generate high-margin revenue. Data marketplace creates network effects.', 'Q3 revenue: $2.1M (up 40% QoQ). Professional services: 45% margins. Data marketplace early stage but 3 partnerships signed. Customer LTV: $340k, CAC: $45k (7.5x ratio).', 'Data marketplace revenue model still experimental and unproven at scale.', '{"q3_revenue": 2100000, "revenue_growth_qoq": 0.40, "ltv_cac_ratio": 7.5, "services_margin": 0.45}'),

('550e8400-e29b-41d4-a716-446655440001', 'Ticket Size & Traction Fit', 2.2, 0.87, 'Perfect fit for Series A funding. $3.5M request aligns with current traction and 18-month runway. Clear milestones tied to funding: 10x ARR growth, team scaling, international expansion.', '$3.5M will fund 18 months of operations. Plan to scale from $2.1M to $25M ARR. Team growth from 23 to 65 people. Clear international expansion budget of $800k.', 'Burn rate assumptions may be optimistic given current hiring market conditions.', '{"funding_request": 3500000, "runway_months": 18, "arr_target": 25000000, "team_growth_target": 65}'),

('550e8400-e29b-41d4-a716-446655440001', 'Market', 2.3, 0.89, 'Large addressable market in data infrastructure ($47B by 2025). Growing at 23% CAGR. Positioned well against incumbents with differentiated AI-first approach.', 'TAM: $47B by 2025. SAM: $8.2B for AI-powered data platforms. Current market growing 23% annually. 3 main competitors: Palantir ($20B valuation), Snowflake ($70B), Databricks ($38B).', 'Market saturation risk as big tech companies (Google, AWS, Microsoft) expand data platform offerings.', '{"tam_2025": 47000000000, "sam": 8200000000, "market_growth_cagr": 0.23, "main_competitors": 3}'),

('550e8400-e29b-41d4-a716-446655440001', 'Revenue & Traction', 1.7, 0.93, 'Outstanding revenue growth: 40% month-over-month for 8 consecutive months. $2.1M quarterly revenue with clear path to $10M+ ARR. Strong customer retention at 96%.', 'Q3 2024: $2.1M revenue. 8 months of 40% MoM growth. Customer retention: 96%. Net revenue retention: 145%. 47 paying customers, average contract: $67k annually.', 'None - revenue metrics are well-documented and verified by third-party accountants.', '{"q3_revenue": 2100000, "mom_growth": 0.40, "retention_rate": 0.96, "nrr": 1.45, "paying_customers": 47}'),

('550e8400-e29b-41d4-a716-446655440001', 'IP', 2.5, 0.78, 'Strong IP portfolio with 15 patents filed in AI/ML data processing. 8 patents already granted. Some overlap with existing patents in the space creates minor risk.', '15 patents filed, 8 granted in US. 3 international patents pending. Core algorithms have trade secret protection. Freedom to operate analysis shows 92% clearance.', 'Potential patent conflict with IBM on distributed data processing methods. Legal review ongoing for 2 patent applications.', '{"patents_filed": 15, "patents_granted": 8, "international_pending": 3, "fto_clearance": 0.92}'),

('550e8400-e29b-41d4-a716-446655440001', 'Competition', 2.7, 0.82, 'Competitive market with established players, but NeuralFlow has clear differentiation through AI-first approach. Competitive advantage in performance and ease of use.', 'Main competitors: Palantir (enterprise focus), Snowflake (data warehousing), Databricks (analytics). NeuralFlow shows 3x better performance in benchmarks. Lower complexity scores in user testing.', 'Risk of competitive response from well-funded incumbents. AWS, Google Cloud expanding into this space with significant resources.', '{"main_competitors": 3, "performance_advantage": "3x", "competitive_threats": "Big Tech expansion"}');

-- EcoTech Solutions (550e8400-e29b-41d4-a716-446655440002) criteria scores  
INSERT INTO criteria_scores (deal_id, criterion, score, confidence, rationale, evidence, missing_data, raw) VALUES
('550e8400-e29b-41d4-a716-446655440002', 'Team', 3.2, 0.79, 'Solid team led by Marcus Green (environmental engineer, 12 years experience) and Lisa Wang (former McKinsey consultant). Team lacks previous startup experience and technical depth in software development.', 'CEO has strong domain expertise in sustainability consulting. CTO has 8 years at SAP but limited early-stage experience. Team of 12 people, only 4 engineers. No previous exits among leadership.', 'Concerns about team scalability and ability to attract senior technical talent in competitive market.', '{"team_size": 12, "founders": 2, "engineers": 4, "previous_exits": 0, "domain_experience": "strong"}'),

('550e8400-e29b-41d4-a716-446655440002', 'Business Model', 3.0, 0.83, 'B2B SaaS model targeting supply chain carbon tracking. Recurring revenue model with per-supplier pricing. Model validation through 23 paying customers, but pricing pressure evident.', 'Monthly recurring revenue: $87k. Average contract: $3.8k monthly. 23 paying customers across manufacturing and retail. Gross margins: 76%. Some customers requesting pricing discounts.', 'Customer concentration risk with top 3 customers representing 45% of revenue. Pricing model may not scale effectively.', '{"mrr": 87000, "avg_contract_monthly": 3800, "paying_customers": 23, "gross_margin": 0.76, "top3_concentration": 0.45}'),

('550e8400-e29b-41d4-a716-446655440002', 'Technology', 3.5, 0.71, 'Functional platform for carbon footprint tracking but technology stack appears dated. Using primarily off-the-shelf components with limited proprietary technology development.', 'Platform built on React/Node.js with standard integrations to ERP systems. No significant IP or patents. Relies heavily on third-party data providers. Basic machine learning for carbon calculations.', 'Technology debt concerns. Platform scalability questions for enterprise customers. Limited differentiation from competitors like Watershed and Persefoni.', '{"tech_stack": "Standard", "patents": 0, "proprietary_tech": "Limited", "scalability_concerns": "Yes"}'),

('550e8400-e29b-41d4-a716-446655440002', 'Product', 3.1, 0.85, 'Working product with reasonable user adoption among current customers. User interface needs improvement. Feature set covers basic carbon tracking needs but lacks advanced analytics.', 'Customer satisfaction score: 7.2/10. Core features: carbon tracking, supplier onboarding, basic reporting. 67% feature utilization rate. 3 customer interviews revealed UX improvement needs.', 'Product roadmap lacks clear prioritization. Customer requests for advanced features are not being addressed quickly enough.', '{"satisfaction_score": 7.2, "core_features": 3, "utilization_rate": 0.67, "customer_interviews": 3}'),

('550e8400-e29b-41d4-a716-446655440002', 'Geography', 2.9, 0.88, 'European market focus aligns with strong sustainability regulations (EU taxonomy, CSRD). Good positioning for regulatory compliance requirements. Limited presence outside EU.', 'Based in Berlin, Germany. 78% customers in EU, 22% in UK. Strong understanding of EU sustainability regulations. GDPR compliant. Limited US market presence.', 'US market expansion strategy unclear. Different regulatory environment in Asia-Pacific not well understood.', '{"primary_market": "Europe", "eu_customers": 0.78, "regulatory_compliance": "Strong", "us_presence": "Limited"}'),

('550e8400-e29b-41d4-a716-446655440002', 'Monetization', 3.3, 0.80, 'Revenue model working but facing pricing pressure. Monthly recurring revenue of $87k shows some traction but growth has plateaued in recent months.', 'Q3 revenue: $261k (up 12% QoQ). Customer LTV: $45k, CAC: $12k (3.75x ratio). Revenue growth slowing from previous 25% QoQ. Some customers downgrading plans.', 'Pricing pressure from competitors. Customer acquisition costs rising. Revenue growth trajectory concerning for scaling.', '{"q3_revenue": 261000, "revenue_growth_qoq": 0.12, "ltv_cac_ratio": 3.75, "growth_trend": "Slowing"}'),

('550e8400-e29b-41d4-a716-446655440002', 'Ticket Size & Traction Fit', 3.4, 0.76, 'Seed funding request of $1.2M seems reasonable for current stage but traction metrics suggest challenges in reaching next milestone efficiently.', '$1.2M for 12-month runway. Plan to grow from $1M to $5M ARR. Team expansion from 12 to 20 people. Burn rate: $95k monthly.', 'Revenue growth assumptions may be optimistic given recent slowdown. Market development costs potentially underestimated.', '{"funding_request": 1200000, "runway_months": 12, "arr_target": 5000000, "monthly_burn": 95000}'),

('550e8400-e29b-41d4-a716-446655440002', 'Market', 2.8, 0.86, 'Carbon tracking market growing rapidly due to regulatory requirements. Market size estimated at $15B by 2027. High fragmentation creates opportunities but also competitive threats.', 'Carbon management market: $15B by 2027, growing 25% CAGR. Drivers: EU taxonomy, CSRD, corporate sustainability commitments. 200+ competitors globally, mostly small players.', 'Market highly fragmented with new entrants constantly. Large consulting firms (Deloitte, PwC) expanding service offerings in this space.', '{"market_size_2027": 15000000000, "cagr": 0.25, "competitors": "200+", "fragmentation": "High"}'),

('550e8400-e29b-41d4-a716-446655440002', 'Revenue & Traction', 3.6, 0.84, 'Revenue growth has slowed significantly in recent quarters. From 25% QoQ to 12% QoQ. Customer acquisition appears to be getting more challenging.', 'Q3 2024: $261k revenue. Growth slowed to 12% QoQ from previous 25%. Customer churn: 8% monthly. 23 paying customers, average $3.8k monthly contract.', 'Revenue trajectory shows concerning deceleration. Customer acquisition challenges becoming apparent.', '{"q3_revenue": 261000, "revenue_growth_current": 0.12, "revenue_growth_previous": 0.25, "monthly_churn": 0.08}'),

('550e8400-e29b-41d4-a716-446655440002', 'IP', 4.1, 0.89, 'Limited intellectual property portfolio. No patents filed. Primarily relying on trade secrets and customer relationships for competitive protection.', 'No patents or patent applications. Basic trademark protection for company name. Limited proprietary algorithms. Mostly using industry-standard methodologies for carbon calculations.', 'Weak IP position creates vulnerability to larger competitors. No significant barriers to entry from IP perspective.', '{"patents": 0, "trademarks": 1, "proprietary_algorithms": "Limited", "competitive_moat": "Weak"}'),

('550e8400-e29b-41d4-a716-446655440002', 'Competition', 3.8, 0.81, 'Highly competitive market with both startup and enterprise players. Limited differentiation from competitors like Watershed, Persefoni, and Sphera. Competitive positioning unclear.', 'Main competitors: Watershed ($100M+ funding), Persefoni ($101M funding), Sphera (public company). EcoTech positioned as "affordable alternative" but feature gaps evident.', 'Strong competitive pressure from well-funded players. Large enterprises like Microsoft, SAP developing competing solutions.', '{"funded_competitors": 3, "competitive_funding": "100M+", "positioning": "Affordable alternative", "enterprise_threats": "Yes"}');