-- Insert sample criteria scores for the existing deal
INSERT INTO public.criteria_scores (deal_id, criterion, score, confidence, rationale, evidence, missing_data, raw) VALUES
('550e8400-e29b-41d4-a716-446655440001', 'Team', 2.0, 0.85, 'Strong founding team with previous exits and deep domain expertise in AI/ML. CEO has Stanford PhD in CS and CTO previously led engineering at unicorn startup.', 'LinkedIn profiles show extensive experience. Previous company acquired for $180M. Technical publications in top-tier conferences.', 'None', '{"team_size": 8, "previous_exits": 1, "technical_publications": 12, "avg_experience_years": 8.5}'),
('550e8400-e29b-41d4-a716-446655440001', 'Business Model', 2.5, 0.78, 'SaaS model with enterprise contracts. Strong recurring revenue but customer concentration risk with top 3 clients representing 60% of revenue.', 'Monthly recurring revenue of $280k with 95% retention rate. Average contract value of $50k annually.', 'Limited information about customer acquisition cost and lifetime value ratios', '{"mrr": 280000, "retention_rate": 0.95, "top_3_client_concentration": 0.6, "avg_contract_value": 50000}'),
('550e8400-e29b-41d4-a716-446655440001', 'Technology', 1.8, 0.92, 'Proprietary ML algorithms with significant technical differentiation. Patent portfolio provides competitive moat. Proven scalability handling enterprise workloads.', 'Multiple granted patents in automated pipeline optimization. Technical benchmarks show 3x performance improvement over competitors.', 'None', '{"patents_granted": 5, "performance_improvement": "3x", "enterprise_clients": 15, "uptime": 0.999}'),
('550e8400-e29b-41d4-a716-446655440001', 'Product', 2.2, 0.80, 'Well-developed product with strong user adoption metrics. Regular feature releases based on customer feedback. Some gaps in enterprise security features.', 'NPS score of 72. Weekly active user growth of 15%. Feature request implementation rate of 80%.', 'Enterprise security certifications (SOC2, GDPR compliance) still in progress', '{"nps_score": 72, "wau_growth": 0.15, "feature_implementation_rate": 0.8}'),
('550e8400-e29b-41d4-a716-446655440001', 'Geography', 2.0, 0.88, 'North American market with expansion plans to Europe. Strong presence in target geographic segments with established partnerships.', 'Customers across 15 US states and 2 Canadian provinces. Partnership agreements with 3 major consulting firms.', 'None', '{"geographic_coverage": "North America", "states_provinces": 17, "partnerships": 3}'),
('550e8400-e29b-41d4-a716-446655440001', 'Monetization', 2.4, 0.75, 'Multiple revenue streams with subscription base and professional services. Good pricing power but limited upselling to existing customers.', 'Average revenue per user increasing 12% quarterly. Professional services margin of 35%.', 'Detailed analysis of customer lifetime value and churn patterns', '{"arpu_growth": 0.12, "services_margin": 0.35, "revenue_streams": 2}'),
('550e8400-e29b-41d4-a716-446655440001', 'Ticket Size & Traction Fit', 1.9, 0.82, 'Perfect alignment with Series A funding requirements. Strong traction metrics justify valuation and investment thesis.', '$3.5M raise matches growth trajectory and market opportunity. Revenue run rate supports 3-4x revenue multiple.', 'None', '{"funding_amount": 3500000, "revenue_multiple": 3.2, "growth_trajectory": "hockey_stick"}'),
('550e8400-e29b-41d4-a716-446655440001', 'Market', 2.1, 0.86, 'Large addressable market with favorable tailwinds. Growing demand for AI automation in enterprise data operations.', 'TAM of $45B with 25% annual growth rate. Market research shows increasing enterprise adoption of ML automation.', 'None', '{"tam": 45000000000, "market_growth_rate": 0.25, "enterprise_adoption_trend": "increasing"}'),
('550e8400-e29b-41d4-a716-446655440001', 'Revenue & Traction', 2.3, 0.91, 'Strong revenue growth with improving unit economics. Path to profitability clear within 18 months based on current trajectory.', 'Revenue growing 40% month-over-month. Gross margin improving from 65% to 78% over past year.', 'None', '{"revenue_growth_mom": 0.4, "gross_margin": 0.78, "path_to_profitability_months": 18}'),
('550e8400-e29b-41d4-a716-446655440001', 'IP', 2.6, 0.70, 'Solid patent portfolio but some concerns about competitive positioning as larger tech companies enter the space.', 'Portfolio includes 5 granted patents and 3 pending applications. Some overlap with recent Google research publications.', 'Comprehensive competitive IP analysis and freedom to operate assessment', '{"patents_granted": 5, "patents_pending": 3, "competitive_overlap": "moderate"}'),
('550e8400-e29b-41d4-a716-446655440001', 'Competition', 2.8, 0.77, 'Competitive landscape intensifying with both startups and big tech players. Company has first-mover advantage but needs to execute quickly.', 'Currently #2 market position with 12% market share. Main competitor raised $50M Series B last quarter.', 'Detailed competitive feature comparison and market positioning analysis', '{"market_position": 2, "market_share": 0.12, "main_competitor_funding": 50000000}');